#!/bin/sh -e

vim_server_name=VIM

target1=
target2=
sleep=
parent_process=`ps -U ${USER} | grep -e ${PPID} | grep -oe '[[:graph:]]\+$'`
case ${parent_process} in
svn)
	target1=`readlink -m $6`
	target2=`readlink -m $7`
	;;
git)
	target1=`readlink -m $2`
	target2=`readlink -m $5`
	sleep=1
	;;
*)
	target1=`readlink -m $1`
	target2=`readlink -m $2`
esac

cat <<EOF | grep -qe '\.\(d\|o\|lo\|html\|jpg\|bdf\|gcda\|gcno\|info\|log\|xml\)$' && echo Skipped: "'${target1}'" "'${target2}'" && exit 0
${target1}
${target2}
EOF

! vim --version | grep -qe '+clientserver' &&
	echo Error, Vim with "'clientserver'" feature is required, but your Vim does not have the feature... && exit 1
! vim --serverlist | grep -qe ^${vim_server_name}\$ &&
	echo Error, Vim server "'${vim_server_name}'" is not running. Try again after "'\$vim --servername ${vim_server_name}'" on another tty.  && exit 1

vim --servername ${vim_server_name} --remote-tab +"\
	set nocompatible |\
	syntax on |\
	filetype plugin indent on |\
	set splitright |\
	set fillchars=diff:\\  |\
	set diffopt=filler,vertical |\
	set t_Co=256 |\
	colorscheme morning |\
	highlight DiffAdd    ctermfg=black ctermbg=lightblue   guifg=black guibg=lightblue |\
	highlight DiffChange ctermfg=black ctermbg=lightyellow guifg=black guibg=yellow    |\
	highlight DiffDelete               ctermbg=lightred    guifg=white guibg=lightred  |\
	highlight DiffText   ctermfg=white ctermbg=red         guifg=white guibg=red       |\
	view ${target1} |\
	diffthis |\
	diffsplit ${target2} |\
	let t:filetype = &filetype |\
	wincmd h |\
	let &filetype = t:filetype |\
	wincmd l |\
	windo set nofoldenable" /dev/null
[ -n "${sleep}" ] && sleep ${sleep}
exit 0
