#!/bin/sh -e

command=`basename ${0}`
diff_option=
parent=`ps -U ${USER} | grep -e ${PPID} | grep -oe '[[:graph:]]\+$'`
case ${parent} in
svn)
	diff_option=${1}
	while [ ${2} != -L ]; do diff_option="${diff_option} ${2}"; shift; done
	target1=${6}
	target2=${7}
	sleep=1
	;;
git)
	target1=${2}
	target2=${5}
	sleep=1
	;;
*)
	target1=${1}
	target2=${2}
	sleep=
esac

grep -qe '\.\(d\|o\|lo\|html\|jpg\|bdf\|gcda\|gcno\|info\|log\|xml\)$' <<EOF && echo Skipped: "'${target1}'" "'${target2}'" && exit 0
${target1}
${target2}
EOF

vim_diff()
{
	error_happened=
	vim_servername=VIM
	while getopts s: arg; do
		case ${arg} in
		s) vim_servername=${OPTARG};;
		esac
	done
	shift `expr ${OPTIND} - 1`

	trap '[ -n "${sleep}" -a -n "${error_happened}" ] && kill ${PPID}' EXIT
	! which vim > /dev/null && echo Error. Vim not found. && { error_happened=true; return 1;}
	! vim --version | grep -qe '+clientserver' &&
		echo Error. Vim with "'clientserver'" feature is required, but your Vim does not have the feature... >&2 && { error_happened=true; return 1;}
	! vim --serverlist | grep -qe ^${vim_servername}\$ &&
		echo Error. Vim server "'${vim_servername}'" is not running or X server is not running. Try again after "'\$ vim --servername ${vim_servername}'" on another tty. >&2 && { error_happened=true; return 1;}

	echo ${1} | grep -qe '^/tmp/svn-\|/\.svn/' && { tmp1=`mktemp --tmpdir ${command}.XXXXXX`; cp ${1} ${tmp1};}
	echo ${2} | grep -qe '^/tmp/svn-\|/\.svn/' && { tmp2=`mktemp --tmpdir ${command}.XXXXXX`; cp ${2} ${tmp2};}
	set ${tmp1:-${1}} ${tmp2:-${2}}

	vim --servername ${vim_servername} --remote-tab +"\
set nocompatible | \
syntax on | \
filetype plugin indent on | \
set splitright | \
set fillchars=diff:\\  | \
set diffopt=filler,vertical | \
set t_Co=256 | \
colorscheme morning | \
highlight DiffAdd    ctermfg=black ctermbg=lightblue   guifg=black guibg=lightblue | \
highlight DiffChange ctermfg=black ctermbg=lightyellow guifg=black guibg=yellow    | \
highlight DiffDelete               ctermbg=lightred    guifg=white guibg=lightred  | \
highlight DiffText   ctermfg=white ctermbg=red         guifg=white guibg=red       | \
view `readlink -m ${1}` | \
diffthis | \
diffsplit `readlink -m ${2}` | \
let t:filetype = &filetype | \
wincmd h | \
let &filetype = t:filetype | \
wincmd l | \
windo set nofoldenable | \
augroup ${command} | \
autocmd VimLeave * !rm -f ${tmp1} ${tmp2}" /dev/null
	[ -n "${sleep}" ] && sleep ${sleep}
}

invoke_diff()
{
	case "${diff_option}" in
	*--orig*)
		diff `echo ${diff_option} | sed -e 's/--orig//'` ${1} ${2};;
	*)
		vim_diff ${1} ${2};;
	esac
}

invoke_diff ${target1} ${target2}
