#!/bin/sh -e

vimserver=VIM

! vim --version | grep -q -e '+clientserver' &&
	echo Error, Vim with "'clientserver'" feature is required, but your Vim does not have the feature... && exit 1
! vim --serverlist | grep -q -e ${vimserver} &&
	echo Error, Vim server "'${vimserver}'" is not running. Try again after "'\$vim --servername ${vimserver}'" on another tty.  && exit 1

cat <<EOF | grep -q -e '\.\(html\|jpg\|bdf\|d\|gcda\|gcno\)$' && echo Skipped: "'$6'" "'$7'" && exit 0
$6
$7
EOF

vim --servername VIM --remote-tab +"view $6 | diffthis | vertical diffsplit $7 | windo %foldopen!" /dev/null
